export const VALIDATE_FORM = "VALIDATE_FORM";
export const VALIDATE_FORM_SUCCESS = "VALIDATE_FORM_SUCCESS";
export const VALIDATE_FORM_ERROR = "VALIDATE_FORM_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_DOWNLOAD_PRODUCTS = "START_DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODDUCTS_ERROR = "DOWNLOAD_PRODDUCTS_ERROR";

export const GET_PRODUCT_DELETED = "GET_PRODUCT_DELETED";
export const PRODUCT_DELETED_SUCCESS = "PRODUCT_DELETED_SUCCESS";
export const PRODUCT_DELETED_ERROR = "PRODUCT_DELETED_ERROR";
